import {publicClient,walletClient,ensureStudionet,type TxPhase} from '../wallet/client'; import {registryAbi,vaultAbi} from './abi'; import type {Address,EIP1193Provider,Hash} from 'viem'; export type {TxPhase} from '../wallet/client';
const vault=(process.env.NEXT_PUBLIC_VAULT_ADDRESS||'') as Address;
const registry=(process.env.NEXT_PUBLIC_REGISTRY_ADDRESS||'') as Address;
export function configured(){return Boolean(registry&&vault)}
export async function readCanonicalVault(){if(!registry) throw new Error('Registry address is not configured'); return publicClient.readContract({address:registry,abi:registryAbi,functionName:'get_canonical_vault',args:[]})}
export async function readCovenantCount(){if(!registry)throw new Error('Registry address is not configured');return publicClient.readContract({address:registry,abi:registryAbi,functionName:'get_covenant_count',args:[]})}
export async function readCovenant(id:bigint){if(!registry) throw new Error('Registry address is not configured');return publicClient.readContract({address:registry,abi:registryAbi,functionName:'get_covenant',args:[id]})}
export async function auditDue(id:bigint){if(!registry)throw new Error('Registry address is not configured');return publicClient.readContract({address:registry,abi:registryAbi,functionName:'is_audit_due',args:[id]})}
export async function readAudit(id:string){if(!registry)throw new Error('Registry address is not configured');return publicClient.readContract({address:registry,abi:registryAbi,functionName:'get_audit',args:[id]})}
export async function runAudit(provider:EIP1193Provider,id:bigint,onPhase?:(p:TxPhase)=>void){if(!registry)throw new Error('Registry address is not configured');await ensureStudionet(provider);const client=walletClient(provider);const [account]=await client.getAddresses();onPhase?.('AWAITING_SIGNATURE');const hash=await client.writeContract({account,address:registry,abi:registryAbi,functionName:'run_audit',args:[id]});onPhase?.('SUBMITTED');const receipt=await publicClient.waitForTransactionReceipt({hash});if(receipt.status!=='success'){onPhase?.('FAILED');throw new Error('Audit execution failed')}onPhase?.('FINALIZED');onPhase?.('EXECUTION_CONFIRMED');return hash as Hash}
export async function activateCovenant(provider:EIP1193Provider,id:bigint,onPhase?:(p:TxPhase)=>void){if(!registry)throw new Error('Registry address is not configured');await ensureStudionet(provider);const client=walletClient(provider);const [account]=await client.getAddresses();onPhase?.('AWAITING_SIGNATURE');const hash=await client.writeContract({account,address:registry,abi:registryAbi,functionName:'activate',args:[id]});onPhase?.('SUBMITTED');const receipt=await publicClient.waitForTransactionReceipt({hash});if(receipt.status!=='success'){onPhase?.('FAILED');throw new Error('Activation execution failed')}onPhase?.('FINALIZED');onPhase?.('EXECUTION_CONFIRMED');return hash as Hash}
export async function createCovenant(provider:EIP1193Provider,args:{service:string;description:string;recovery:Address;minimumBond:bigint;interval:bigint;term:bigint;clauses:{clause_id:number;text:string;slash_bps:number;minimum_sources:number}[];sources:{source_id:number;url:string}[]},onPhase?:(p:TxPhase)=>void){if(!registry)throw new Error('Registry address is not configured');await ensureStudionet(provider);const client=walletClient(provider);const [account]=await client.getAddresses();onPhase?.('AWAITING_SIGNATURE');const hash=await client.writeContract({account,address:registry,abi:registryAbi,functionName:'create_covenant',args:[args.service,args.description,args.recovery,args.minimumBond,args.interval,args.term,args.clauses,args.sources]});onPhase?.('SUBMITTED');const receipt=await publicClient.waitForTransactionReceipt({hash});if(receipt.status!=='success'){onPhase?.('FAILED');throw new Error('Registry execution failed')}onPhase?.('FINALIZED');onPhase?.('EXECUTION_CONFIRMED');return hash as Hash}
export async function readBond(id:bigint){if(!vault) throw new Error('Vault address is not configured'); return publicClient.readContract({address:vault,abi:vaultAbi,functionName:'get_bond',args:[id]})}
export async function readPrincipal(id:bigint){if(!vault)throw new Error('Vault address is not configured');return publicClient.readContract({address:vault,abi:vaultAbi,functionName:'get_principal',args:[id]})}
export async function readConsumedSlashBps(id:bigint){if(!vault)throw new Error('Vault address is not configured');return publicClient.readContract({address:vault,abi:vaultAbi,functionName:'get_consumed_slash_bps',args:[id]})}
export async function readSlashedAmount(id:bigint){if(!vault)throw new Error('Vault address is not configured');return publicClient.readContract({address:vault,abi:vaultAbi,functionName:'get_slashed_amount',args:[id]})}
export async function readPendingSlashCount(id:bigint){if(!vault)throw new Error('Vault address is not configured');return publicClient.readContract({address:vault,abi:vaultAbi,functionName:'get_pending_slash_count',args:[id]})}
export async function depositBond(provider:EIP1193Provider,id:bigint,value:bigint,onPhase?:(p:TxPhase)=>void){if(!vault)throw new Error('Vault address is not configured'); await ensureStudionet(provider); const client=walletClient(provider); const [account]=await client.getAddresses(); onPhase?.('AWAITING_SIGNATURE'); const hash=await client.writeContract({account,address:vault,abi:vaultAbi,functionName:'deposit_bond',args:[id],value}); onPhase?.('SUBMITTED'); const receipt=await publicClient.waitForTransactionReceipt({hash}); onPhase?.('FINALIZED'); if(receipt.status!=='success'){onPhase?.('FAILED');throw new Error('GenVM execution failed')} onPhase?.('EXECUTION_CONFIRMED'); return hash as Hash}
async function registryWrite(provider:EIP1193Provider,functionName:'refresh_expiry'|'mark_closed',id:bigint,onPhase?:(p:TxPhase)=>void){if(!registry)throw new Error('Registry address is not configured');await ensureStudionet(provider);const client=walletClient(provider);const [account]=await client.getAddresses();onPhase?.('AWAITING_SIGNATURE');const hash=await client.writeContract({account,address:registry,abi:registryAbi,functionName,args:[id]});onPhase?.('SUBMITTED');const receipt=await publicClient.waitForTransactionReceipt({hash});if(receipt.status!=='success'){onPhase?.('FAILED');throw new Error('Registry execution failed')}onPhase?.('FINALIZED');onPhase?.('EXECUTION_CONFIRMED');return hash as Hash}
export const refreshExpiry=(provider:EIP1193Provider,id:bigint,onPhase?:(p:TxPhase)=>void)=>registryWrite(provider,'refresh_expiry',id,onPhase);
export const markClosed=(provider:EIP1193Provider,id:bigint,onPhase?:(p:TxPhase)=>void)=>registryWrite(provider,'mark_closed',id,onPhase);
export async function applySlash(provider:EIP1193Provider,covenantId:bigint,auditId:string,onPhase?:(p:TxPhase)=>void){if(!vault)throw new Error('Vault address is not configured');await ensureStudionet(provider);const client=walletClient(provider);const [account]=await client.getAddresses();onPhase?.('AWAITING_SIGNATURE');const hash=await client.writeContract({account,address:vault,abi:vaultAbi,functionName:'apply_slash',args:[covenantId,auditId]});onPhase?.('SUBMITTED');const receipt=await publicClient.waitForTransactionReceipt({hash});if(receipt.status!=='success'){onPhase?.('FAILED');throw new Error('Vault execution failed')}onPhase?.('FINALIZED');onPhase?.('EXECUTION_CONFIRMED');return hash as Hash}
export async function closeAndRefund(provider:EIP1193Provider,id:bigint,onPhase?:(p:TxPhase)=>void){if(!vault)throw new Error('Vault address is not configured');await ensureStudionet(provider);const client=walletClient(provider);const [account]=await client.getAddresses();onPhase?.('AWAITING_SIGNATURE');const hash=await client.writeContract({account,address:vault,abi:vaultAbi,functionName:'close_and_refund',args:[id]});onPhase?.('SUBMITTED');const receipt=await publicClient.waitForTransactionReceipt({hash});if(receipt.status!=='success'){onPhase?.('FAILED');throw new Error('Vault execution failed')}onPhase?.('FINALIZED');onPhase?.('EXECUTION_CONFIRMED');return hash as Hash}
